package org.tonylin.stock;

public enum StockInfoCategory {
	INVOICE_TM, BUSINESS_INCOMING_TM, COMBINED_BUSINESS_INCOMING_TM, // 本月
	INVOICE_LY, BUSINESS_INCOMING_LY, COMBINED_BUSINESS_INCOMING_LY, // 去年同期
	INVOICE_AS1, BUSINESS_INCOMING_AS1, COMBINED_BUSINESS_INCOMING_AS1, // 增減金額
	INVOICE_ASP1, BUSINESS_INCOMING_ASP1, COMBINED_BUSINESS_INCOMING_ASP1, // 增減百分比
	INVOICE_TYS, BUSINESS_INCOMING_TYS,COMBINED_BUSINESS_INCOMING_TYS, // 本年累計
	INVOICE_LYS, BUSINESS_INCOMING_LYS,COMBINED_BUSINESS_INCOMING_LYS, // 去年累計
	INVOICE_AS2, BUSINESS_INCOMING_AS2, COMBINED_BUSINESS_INCOMING_AS2, // 增減金額
	INVOICE_ASP2, BUSINESS_INCOMING_ASP2,COMBINED_BUSINESS_INCOMING_ASP2  // 增減百分比
}
